image: ubuntu:18.04

stages:
 - build
 - later

build:
  stage: build
  script:
   - apt-get update && apt-get install -y curl
   - curl -sL https://deb.nodesource.com/setup_12.x | bash -
   - apt-get install -y nodejs
   - npm i && npm run build
  artifacts:
    paths:
      - www

pages:
  stage: later
  script:
    - cp -pR www public
  artifacts:
    paths:
      - public
  only:
    - master
