/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface Epi2meDownload {
    'downloads': string;
    'platform': string;
    'product': string;
    'root': string;
  }
}

declare global {


  interface HTMLEpi2meDownloadElement extends Components.Epi2meDownload, HTMLStencilElement {}
  var HTMLEpi2meDownloadElement: {
    prototype: HTMLEpi2meDownloadElement;
    new (): HTMLEpi2meDownloadElement;
  };
  interface HTMLElementTagNameMap {
    'epi2me-download': HTMLEpi2meDownloadElement;
  }
}

declare namespace LocalJSX {
  interface Epi2meDownload {
    'downloads'?: string;
    'platform'?: string;
    'product'?: string;
    'root'?: string;
  }

  interface IntrinsicElements {
    'epi2me-download': Epi2meDownload;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'epi2me-download': LocalJSX.Epi2meDownload & JSXBase.HTMLAttributes<HTMLEpi2meDownloadElement>;
    }
  }
}


